title: How Does Type Work?
description: Explaining the functioning of typography in different brands
header_text: ""
footer_text: Copyright 2020 Yasmin Arnould
header_feature_image: ../uploads/bannerimage3rock.png
bannerheight: 20vmax
logo: ../uploads/logorect3rock.png
favicon: ../uploads/favicon-32x32.png
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About me
    siteurl: /aboutme
    tab: false
