title: How Important Is Type?
description: Explaining the importance of typography in different brands
header_text: Behind the Type
footer_text: Copyright 2020 Yasmin Arnould
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
