title: How Does Type Work?
description: Explaining the functioning of typography in different brands
header_text: Behind the Type
footer_text: Copyright 2020 Yasmin Arnould
header_feature_image: ../uploads/banner1-1.png
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items: []
