title: How Does Type Work?
description: Explaining the functioning of typography in different brands
header_text: ""
footer_text: Copyright 2020 Yasmin Arnould
header_feature_image: ../uploads/banner3.0.png
bannerheight: 20vmax
logo: ../uploads/logo3.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items: []
